// @vitest-environment jsdom

import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import RootLayout, { metadata } from "./layout";

vi.mock("./globals.css", () => ({}), { virtual: true });

vi.mock("next/font/google", () => ({
	Geist: () => ({ variable: "font-geist-sans" }),
	Geist_Mono: () => ({ variable: "font-geist-mono" }),
}));

vi.mock("@clerk/nextjs", () => ({
	ClerkProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

vi.mock("@/components/ConvexClientProvider", () => ({
	default: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

describe("app/layout", () => {
	it("exports the expected metadata", () => {
		expect(metadata.title).toBe("Create Next App");
		expect(metadata.description).toBe("Generated by create next app");
	});

	it("renders children inside the root layout", () => {
		render(
			<RootLayout>
				<div>child</div>
			</RootLayout>,
		);

		expect(screen.getByText("child")).toBeInTheDocument();
		expect(document.body.className).toContain("font-geist-sans");
		expect(document.body.className).toContain("font-geist-mono");
	});
});
